#!/usr/bin/env bash
# Synchronize a local directory with a directory on a remote server
#
# Usage: sync_directory LOCAL_DIR REMOTE_IP REMOTE_USER REMOTE_DIR SSH_KEY_FILE

if [ $# -lt 5 ]; then
  echo "Usage: $0 LOCAL_DIR REMOTE_IP REMOTE_USER REMOTE_DIR SSH_KEY_FILE"
else
  # Use positional parameters directly
  scp -o StrictHostKeyChecking=no -r -i "$5" "$1/" "$3@$2:$4"
fi
