#!/usr/bin/env bash
# Transfer file from client to server
#
# Set variables
if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH IP USERNAME SSH_KEY_PATH"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
