#!/usr/bin/env bash
# Configures a new Ubuntu machine by installing Nginx
# and sets up a custom 404 page

# Update and install Nginx
echo "Updating and installing Nginx..."
sudo apt-get update -y -qq && \
sudo apt-get install nginx -y

# Start Nginx service
sudo service nginx start

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Set permissions for website files
sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www/html

# Backup default index and create new one with "Hello World!"
sudo cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bak
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

# Configure redirection for /redirect_me to a YouTube video
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Set up a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html > /dev/null
sudo sed -i '25i\       error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

echo "Nginx configured for custom 404 page. ✅"
