#!/usr/bin/env bash

# Install HAProxy
sudo apt update
sudo apt install -y haproxy

# Backup the default HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Define HAProxy configuration
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg >/dev/null
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 525492-web-01 100.25.188.51:80 check
    server 525492-web-02 54.209.116.96:80 check
EOF

# Enable HAProxy to be managed via init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy service
sudo service haproxy restart

echo "HAProxy installed and configured successfully."
