#!/usr/bin/env bash
# Install and configure load balancer (HAProxy)

echo -e "Updating packages and performing preliminary checks...\n"

function install() {
    command -v "$1" &> /dev/null

    if [ $? -ne 0 ]; then
        echo -e "Installing: $1\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "$1 is already installed.\n"
    fi
}

# Install HAProxy
install haproxy

echo -e "\nSetting up HAProxy configuration...\n"

# Backup the default HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

# Define HAProxy configuration
server_config="
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend shiks-tech-frontend
    bind *:80
    default_backend shiks-tech-backend

backend shiks-tech-backend
    balance roundrobin
    server 525492-web-01 100.25.188.51:80 check
    server 525492-web-02 54.209.116.96:80 check
"

# Apply the custom HAProxy configuration
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

echo "HAProxy configured with round-robin on 525492-web-01 and 525492-web-02 under shiks.tech domain"

# Restart or start HAProxy service
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi
