#!/usr/bin/env bash
# 101-manage_my_process

manage_script="./manage_my_process"

start_manage() {
    if [ ! -f "$pid_file" ]; then
        "$manage_script" &
        echo "$!" > "$pid_file"
        echo "manage_my_process started"
    else
        echo "manage_my_process is already running."
    fi
}

stop_manage() {
    if [ -f "$pid_file" ]; then
        pid=$(cat "$pid_file")
        kill "$pid"
        rm "$pid_file"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running."
    fi
}

restart_manage() {
    stop_manage
    start_manage
    echo "manage_my_process restarted"
}

pid_file="/var/run/my_process.pid"

case "$1" in
    start)
        start_manage
        ;;
    stop)
        stop_manage
        ;;
    restart)
        restart_manage
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
