#!/usr/bin/env bash
# manage_my_process

pid_file="/var/run/my_process.pid"
message="I am alive!"

cleanup_and_exit() {
    echo "Stopping manage_my_process..."
    rm "$pid_file"
    exit 0
}

echo $$ > "$pid_file"
echo "manage_my_process started"

trap cleanup_and_exit SIGTERM

while true; do
    echo "$message" >> /tmp/my_process
    sleep 2
done
