#!/usr/bin/env bash
# Script to display messages based on loop iteration

# Initialize counter
counter=1

# Loop while counter is less than or equal to 10
while [ $count -lt 10 ]
do
  if [ $count -eq 3 ]
  then
    echo "bad luck"
  elif [ $count -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( count++ ))
done
