#!/usr/bin/env bash
# Script to display messages based on loop iteration

# Initialize counter
counter=1

# Loop while counter is less than or equal to 20
while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( count++ ))
done
