#!/usr/bin/env bash
# This script gracefully restarts Gunicorn
PID=$(pgrep -f 'gunicorn')
if [ -z "$PID" ]; then
  echo "Gunicorn is not running."
  exit 1
fi
kill -HUP "$PID"

echo "Gunicorn reloaded successfully."
